kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: alert-manager-to-service-now
  namespace: alert-manager-to-service-now
  labels:
    app: alert-manager-to-service-now
    app.kubernetes.io/component: alert-manager-to-service-now
    app.kubernetes.io/instance: alert-manager-to-service-now
    app.kubernetes.io/name: alert-manager-to-service-now
    app.kubernetes.io/part-of: alert-manager-to-service-now
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'alert-manager-to-service-now:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/tosin2013/alert-manager-to-service-now.git'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: alert-manager-to-service-now-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: alert-manager-to-service-now-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
